### ISSUE TITLE
approve of this version

### ISSUE THREAD

**Issue by AEStapleton** [andrewmcodes/stapleton-gatsby#26]
This looks great; I viewed the new version on mobile and laptop and everything works.  Go ahead and finish it up when you get a chance.

**Comment by andrewmcodes** [comment]
@AEStapleton About to merge a fix for the final issue hanging out. One thing that I thought about while wrapping this up is the home section is painfully plain. If you don't care, I can wrap all this up and get you the files needed but if you are interested in adding something to this section, I really like the free illustrations on [this site](https://undraw.co/illustrations). Maybe one will strike your fancy? Colors are changeable and I can do some advanced customization to sub in a woman if an illustration you like has a male in it.

**Comment by AEStapleton** [comment]
Hi Andrew,

Thanks for all your work on this.  I like modernist, plain things, so the simple site is good with me.  I do know that others prefer more details, so if we can find a good drawing that would be nicr for viewers.  I’ve attached the drawing I have on my office status board —it’s too silly to use on my page, but you can see what I like (information, rather than decoration).  From the illustration site you pointed me to, the ‘in progress’ or ‘status update’ or ‘wireframing’ or ‘analyze’  illustrations might work.

Yours, Ann

On Apr 28, 2019, 9:10 PM -0400, Andrew Mason <notifications@github.com>, wrote:

@AEStapleton<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAEStapleton&data=01%7C01%7Cstapletona%40uncw.edu%7C0d9a1379e7f04185b0a708d6cc3f83ca%7C2213678197534c75af2868a078871ebf%7C1&sdata=%2BzfXd0pnN6Zl11PmGMozwTUAFa643IMrIX%2F905V0vaQ%3D&reserved=0> About to merge a fix for the final issue hanging out. One thing that I thought about while wrapping this up is the home section is painfully plain. If you don't care, I can wrap all this up and get you the files needed but if you are interested in adding something to this section, I really like the free illustrations on this site<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fundraw.co%2Fillustrations&data=01%7C01%7Cstapletona%40uncw.edu%7C0d9a1379e7f04185b0a708d6cc3f83ca%7C2213678197534c75af2868a078871ebf%7C1&sdata=nJzKlmFNwwutOwdZ6vUYYNn%2FaAN88fL4rEic2RBHWgQ%3D&reserved=0>. Maybe one will strike your fancy? Colors are changeable and I can do some advanced customization to sub in a woman if an illustration you like has a male in it.
